version: '3.1'

services:
    postgres:
        image: 'postgres'
        environment:
            - POSTGRES_PASSWORD=admin123
            - POSTGRES_USER=admin
            - POSTGRES_DB=my_store
        ports:
            - 5432:5432
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=root@email.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - 5050:80